version: '3.5'
services:
  telegrambot:
    env_file: .env
    container_name: telegrambot_gpt4free
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
#    volumes:
#      - ./home/personas:/app/personas
